//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BSMS.bsms.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bsms_serviceSoap", Namespace="http://tempuri.org/")]
    public partial class bsms_service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenresOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateGenreOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserGenreOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteGenreOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAuthorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProducersOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProducerOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertProducerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProducerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public bsms_service() {
            this.Url = global::BSMS.Properties.Settings.Default.BSMS_bsms_localhost_bsms_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event GetRolesCompletedEventHandler GetRolesCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetCategoriesCompletedEventHandler GetCategoriesCompleted;
        
        /// <remarks/>
        public event UpdateCategoryCompletedEventHandler UpdateCategoryCompleted;
        
        /// <remarks/>
        public event InserCategoryCompletedEventHandler InserCategoryCompleted;
        
        /// <remarks/>
        public event DeleteCategoryCompletedEventHandler DeleteCategoryCompleted;
        
        /// <remarks/>
        public event GetGenresCompletedEventHandler GetGenresCompleted;
        
        /// <remarks/>
        public event UpdateGenreCompletedEventHandler UpdateGenreCompleted;
        
        /// <remarks/>
        public event InserGenreCompletedEventHandler InserGenreCompleted;
        
        /// <remarks/>
        public event DeleteGenreCompletedEventHandler DeleteGenreCompleted;
        
        /// <remarks/>
        public event DeleteUserCompletedEventHandler DeleteUserCompleted;
        
        /// <remarks/>
        public event GetAuthorsCompletedEventHandler GetAuthorsCompleted;
        
        /// <remarks/>
        public event DeleteAuthorCompletedEventHandler DeleteAuthorCompleted;
        
        /// <remarks/>
        public event AddAuthorCompletedEventHandler AddAuthorCompleted;
        
        /// <remarks/>
        public event UpdateAuthorCompletedEventHandler UpdateAuthorCompleted;
        
        /// <remarks/>
        public event GetProducersCompletedEventHandler GetProducersCompleted;
        
        /// <remarks/>
        public event DeleteProducerCompletedEventHandler DeleteProducerCompleted;
        
        /// <remarks/>
        public event InsertProducerCompletedEventHandler InsertProducerCompleted;
        
        /// <remarks/>
        public event UpdateProducerCompletedEventHandler UpdateProducerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateUser(USER user) {
            this.Invoke("UpdateUser", new object[] {
                        user});
        }
        
        /// <remarks/>
        public void UpdateUserAsync(USER user) {
            this.UpdateUserAsync(user, null);
        }
        
        /// <remarks/>
        public void UpdateUserAsync(USER user, object userState) {
            if ((this.UpdateUserOperationCompleted == null)) {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                        user}, this.UpdateUserOperationCompleted, userState);
        }
        
        private void OnUpdateUserOperationCompleted(object arg) {
            if ((this.UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddUser(USER user) {
            object[] results = this.Invoke("AddUser", new object[] {
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(USER user) {
            this.AddUserAsync(user, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(USER user, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        user}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ROLE[] GetRoles() {
            object[] results = this.Invoke("GetRoles", new object[0]);
            return ((ROLE[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesAsync() {
            this.GetRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetRolesAsync(object userState) {
            if ((this.GetRolesOperationCompleted == null)) {
                this.GetRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesOperationCompleted);
            }
            this.InvokeAsync("GetRoles", new object[0], this.GetRolesOperationCompleted, userState);
        }
        
        private void OnGetRolesOperationCompleted(object arg) {
            if ((this.GetRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesCompleted(this, new GetRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public USER[] GetUsers() {
            object[] results = this.Invoke("GetUsers", new object[0]);
            return ((USER[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync() {
            this.GetUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[0], this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCategories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CATEGORY[] GetCategories() {
            object[] results = this.Invoke("GetCategories", new object[0]);
            return ((CATEGORY[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(object userState) {
            if ((this.GetCategoriesOperationCompleted == null)) {
                this.GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCategories", new object[0], this.GetCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCategoriesOperationCompleted(object arg) {
            if ((this.GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCategory(CATEGORY category) {
            this.Invoke("UpdateCategory", new object[] {
                        category});
        }
        
        /// <remarks/>
        public void UpdateCategoryAsync(CATEGORY category) {
            this.UpdateCategoryAsync(category, null);
        }
        
        /// <remarks/>
        public void UpdateCategoryAsync(CATEGORY category, object userState) {
            if ((this.UpdateCategoryOperationCompleted == null)) {
                this.UpdateCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCategoryOperationCompleted);
            }
            this.InvokeAsync("UpdateCategory", new object[] {
                        category}, this.UpdateCategoryOperationCompleted, userState);
        }
        
        private void OnUpdateCategoryOperationCompleted(object arg) {
            if ((this.UpdateCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCategoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InserCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserCategory(CATEGORY cat) {
            this.Invoke("InserCategory", new object[] {
                        cat});
        }
        
        /// <remarks/>
        public void InserCategoryAsync(CATEGORY cat) {
            this.InserCategoryAsync(cat, null);
        }
        
        /// <remarks/>
        public void InserCategoryAsync(CATEGORY cat, object userState) {
            if ((this.InserCategoryOperationCompleted == null)) {
                this.InserCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserCategoryOperationCompleted);
            }
            this.InvokeAsync("InserCategory", new object[] {
                        cat}, this.InserCategoryOperationCompleted, userState);
        }
        
        private void OnInserCategoryOperationCompleted(object arg) {
            if ((this.InserCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserCategoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCategory(int catID) {
            this.Invoke("DeleteCategory", new object[] {
                        catID});
        }
        
        /// <remarks/>
        public void DeleteCategoryAsync(int catID) {
            this.DeleteCategoryAsync(catID, null);
        }
        
        /// <remarks/>
        public void DeleteCategoryAsync(int catID, object userState) {
            if ((this.DeleteCategoryOperationCompleted == null)) {
                this.DeleteCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCategoryOperationCompleted);
            }
            this.InvokeAsync("DeleteCategory", new object[] {
                        catID}, this.DeleteCategoryOperationCompleted, userState);
        }
        
        private void OnDeleteCategoryOperationCompleted(object arg) {
            if ((this.DeleteCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCategoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGenres", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GENRE[] GetGenres() {
            object[] results = this.Invoke("GetGenres", new object[0]);
            return ((GENRE[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGenresAsync() {
            this.GetGenresAsync(null);
        }
        
        /// <remarks/>
        public void GetGenresAsync(object userState) {
            if ((this.GetGenresOperationCompleted == null)) {
                this.GetGenresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenresOperationCompleted);
            }
            this.InvokeAsync("GetGenres", new object[0], this.GetGenresOperationCompleted, userState);
        }
        
        private void OnGetGenresOperationCompleted(object arg) {
            if ((this.GetGenresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenresCompleted(this, new GetGenresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateGenre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateGenre(GENRE genre) {
            this.Invoke("UpdateGenre", new object[] {
                        genre});
        }
        
        /// <remarks/>
        public void UpdateGenreAsync(GENRE genre) {
            this.UpdateGenreAsync(genre, null);
        }
        
        /// <remarks/>
        public void UpdateGenreAsync(GENRE genre, object userState) {
            if ((this.UpdateGenreOperationCompleted == null)) {
                this.UpdateGenreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGenreOperationCompleted);
            }
            this.InvokeAsync("UpdateGenre", new object[] {
                        genre}, this.UpdateGenreOperationCompleted, userState);
        }
        
        private void OnUpdateGenreOperationCompleted(object arg) {
            if ((this.UpdateGenreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateGenreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InserGenre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserGenre(GENRE genre) {
            this.Invoke("InserGenre", new object[] {
                        genre});
        }
        
        /// <remarks/>
        public void InserGenreAsync(GENRE genre) {
            this.InserGenreAsync(genre, null);
        }
        
        /// <remarks/>
        public void InserGenreAsync(GENRE genre, object userState) {
            if ((this.InserGenreOperationCompleted == null)) {
                this.InserGenreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserGenreOperationCompleted);
            }
            this.InvokeAsync("InserGenre", new object[] {
                        genre}, this.InserGenreOperationCompleted, userState);
        }
        
        private void OnInserGenreOperationCompleted(object arg) {
            if ((this.InserGenreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserGenreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteGenre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteGenre(int genID) {
            this.Invoke("DeleteGenre", new object[] {
                        genID});
        }
        
        /// <remarks/>
        public void DeleteGenreAsync(int genID) {
            this.DeleteGenreAsync(genID, null);
        }
        
        /// <remarks/>
        public void DeleteGenreAsync(int genID, object userState) {
            if ((this.DeleteGenreOperationCompleted == null)) {
                this.DeleteGenreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGenreOperationCompleted);
            }
            this.InvokeAsync("DeleteGenre", new object[] {
                        genID}, this.DeleteGenreOperationCompleted, userState);
        }
        
        private void OnDeleteGenreOperationCompleted(object arg) {
            if ((this.DeleteGenreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteGenreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUser(int uID) {
            this.Invoke("DeleteUser", new object[] {
                        uID});
        }
        
        /// <remarks/>
        public void DeleteUserAsync(int uID) {
            this.DeleteUserAsync(uID, null);
        }
        
        /// <remarks/>
        public void DeleteUserAsync(int uID, object userState) {
            if ((this.DeleteUserOperationCompleted == null)) {
                this.DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUser", new object[] {
                        uID}, this.DeleteUserOperationCompleted, userState);
        }
        
        private void OnDeleteUserOperationCompleted(object arg) {
            if ((this.DeleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAuthors", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AUTHOR[] GetAuthors() {
            object[] results = this.Invoke("GetAuthors", new object[0]);
            return ((AUTHOR[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorsAsync() {
            this.GetAuthorsAsync(null);
        }
        
        /// <remarks/>
        public void GetAuthorsAsync(object userState) {
            if ((this.GetAuthorsOperationCompleted == null)) {
                this.GetAuthorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorsOperationCompleted);
            }
            this.InvokeAsync("GetAuthors", new object[0], this.GetAuthorsOperationCompleted, userState);
        }
        
        private void OnGetAuthorsOperationCompleted(object arg) {
            if ((this.GetAuthorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorsCompleted(this, new GetAuthorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAuthor(int id) {
            this.Invoke("DeleteAuthor", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DeleteAuthorAsync(int id) {
            this.DeleteAuthorAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteAuthorAsync(int id, object userState) {
            if ((this.DeleteAuthorOperationCompleted == null)) {
                this.DeleteAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAuthorOperationCompleted);
            }
            this.InvokeAsync("DeleteAuthor", new object[] {
                        id}, this.DeleteAuthorOperationCompleted, userState);
        }
        
        private void OnDeleteAuthorOperationCompleted(object arg) {
            if ((this.DeleteAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAuthorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddAuthor(AUTHOR author) {
            this.Invoke("AddAuthor", new object[] {
                        author});
        }
        
        /// <remarks/>
        public void AddAuthorAsync(AUTHOR author) {
            this.AddAuthorAsync(author, null);
        }
        
        /// <remarks/>
        public void AddAuthorAsync(AUTHOR author, object userState) {
            if ((this.AddAuthorOperationCompleted == null)) {
                this.AddAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAuthorOperationCompleted);
            }
            this.InvokeAsync("AddAuthor", new object[] {
                        author}, this.AddAuthorOperationCompleted, userState);
        }
        
        private void OnAddAuthorOperationCompleted(object arg) {
            if ((this.AddAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAuthorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAuthor(AUTHOR author) {
            this.Invoke("UpdateAuthor", new object[] {
                        author});
        }
        
        /// <remarks/>
        public void UpdateAuthorAsync(AUTHOR author) {
            this.UpdateAuthorAsync(author, null);
        }
        
        /// <remarks/>
        public void UpdateAuthorAsync(AUTHOR author, object userState) {
            if ((this.UpdateAuthorOperationCompleted == null)) {
                this.UpdateAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAuthorOperationCompleted);
            }
            this.InvokeAsync("UpdateAuthor", new object[] {
                        author}, this.UpdateAuthorOperationCompleted, userState);
        }
        
        private void OnUpdateAuthorOperationCompleted(object arg) {
            if ((this.UpdateAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAuthorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProducers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PRODUCER[] GetProducers() {
            object[] results = this.Invoke("GetProducers", new object[0]);
            return ((PRODUCER[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProducersAsync() {
            this.GetProducersAsync(null);
        }
        
        /// <remarks/>
        public void GetProducersAsync(object userState) {
            if ((this.GetProducersOperationCompleted == null)) {
                this.GetProducersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProducersOperationCompleted);
            }
            this.InvokeAsync("GetProducers", new object[0], this.GetProducersOperationCompleted, userState);
        }
        
        private void OnGetProducersOperationCompleted(object arg) {
            if ((this.GetProducersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProducersCompleted(this, new GetProducersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteProducer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteProducer(int id) {
            this.Invoke("DeleteProducer", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DeleteProducerAsync(int id) {
            this.DeleteProducerAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteProducerAsync(int id, object userState) {
            if ((this.DeleteProducerOperationCompleted == null)) {
                this.DeleteProducerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProducerOperationCompleted);
            }
            this.InvokeAsync("DeleteProducer", new object[] {
                        id}, this.DeleteProducerOperationCompleted, userState);
        }
        
        private void OnDeleteProducerOperationCompleted(object arg) {
            if ((this.DeleteProducerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProducerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertProducer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertProducer(PRODUCER producer) {
            this.Invoke("InsertProducer", new object[] {
                        producer});
        }
        
        /// <remarks/>
        public void InsertProducerAsync(PRODUCER producer) {
            this.InsertProducerAsync(producer, null);
        }
        
        /// <remarks/>
        public void InsertProducerAsync(PRODUCER producer, object userState) {
            if ((this.InsertProducerOperationCompleted == null)) {
                this.InsertProducerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertProducerOperationCompleted);
            }
            this.InvokeAsync("InsertProducer", new object[] {
                        producer}, this.InsertProducerOperationCompleted, userState);
        }
        
        private void OnInsertProducerOperationCompleted(object arg) {
            if ((this.InsertProducerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertProducerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProducer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateProducer(PRODUCER producer) {
            this.Invoke("UpdateProducer", new object[] {
                        producer});
        }
        
        /// <remarks/>
        public void UpdateProducerAsync(PRODUCER producer) {
            this.UpdateProducerAsync(producer, null);
        }
        
        /// <remarks/>
        public void UpdateProducerAsync(PRODUCER producer, object userState) {
            if ((this.UpdateProducerOperationCompleted == null)) {
                this.UpdateProducerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProducerOperationCompleted);
            }
            this.InvokeAsync("UpdateProducer", new object[] {
                        producer}, this.UpdateProducerOperationCompleted, userState);
        }
        
        private void OnUpdateProducerOperationCompleted(object arg) {
            if ((this.UpdateProducerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProducerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class USER {
        
        private int uSERIDField;
        
        private string uSERNAMEField;
        
        private string pASSWORDHASHField;
        
        private string fIRSTNAMEField;
        
        private string lASTNAMEField;
        
        private string mIDDLENAMEField;
        
        private string tHUMBNAIL_PATHField;
        
        private string eMAILField;
        
        private System.Nullable<int> rOLEIDField;
        
        private ROLE rOLEField;
        
        /// <remarks/>
        public int USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PASSWORDHASH {
            get {
                return this.pASSWORDHASHField;
            }
            set {
                this.pASSWORDHASHField = value;
            }
        }
        
        /// <remarks/>
        public string FIRSTNAME {
            get {
                return this.fIRSTNAMEField;
            }
            set {
                this.fIRSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string LASTNAME {
            get {
                return this.lASTNAMEField;
            }
            set {
                this.lASTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MIDDLENAME {
            get {
                return this.mIDDLENAMEField;
            }
            set {
                this.mIDDLENAMEField = value;
            }
        }
        
        /// <remarks/>
        public string THUMBNAIL_PATH {
            get {
                return this.tHUMBNAIL_PATHField;
            }
            set {
                this.tHUMBNAIL_PATHField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ROLEID {
            get {
                return this.rOLEIDField;
            }
            set {
                this.rOLEIDField = value;
            }
        }
        
        /// <remarks/>
        public ROLE ROLE {
            get {
                return this.rOLEField;
            }
            set {
                this.rOLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ROLE {
        
        private int rOLEIDField;
        
        private string rOLE1Field;
        
        /// <remarks/>
        public int ROLEID {
            get {
                return this.rOLEIDField;
            }
            set {
                this.rOLEIDField = value;
            }
        }
        
        /// <remarks/>
        public string ROLE1 {
            get {
                return this.rOLE1Field;
            }
            set {
                this.rOLE1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PRODUCER {
        
        private int pRODUCERIDField;
        
        private string nAMEField;
        
        private string aDDRESSField;
        
        private string cONTACTField;
        
        private string eMAILField;
        
        /// <remarks/>
        public int PRODUCERID {
            get {
                return this.pRODUCERIDField;
            }
            set {
                this.pRODUCERIDField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        public string CONTACT {
            get {
                return this.cONTACTField;
            }
            set {
                this.cONTACTField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AUTHOR {
        
        private int aUTHORIDField;
        
        private string fIRSTNAMEField;
        
        private string lASTNAMEField;
        
        private string mIDDLENAMEField;
        
        private string bIOGRAPHYField;
        
        private string aLIASNAMEField;
        
        private string tHUMBNAIL_PATHField;
        
        /// <remarks/>
        public int AUTHORID {
            get {
                return this.aUTHORIDField;
            }
            set {
                this.aUTHORIDField = value;
            }
        }
        
        /// <remarks/>
        public string FIRSTNAME {
            get {
                return this.fIRSTNAMEField;
            }
            set {
                this.fIRSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string LASTNAME {
            get {
                return this.lASTNAMEField;
            }
            set {
                this.lASTNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MIDDLENAME {
            get {
                return this.mIDDLENAMEField;
            }
            set {
                this.mIDDLENAMEField = value;
            }
        }
        
        /// <remarks/>
        public string BIOGRAPHY {
            get {
                return this.bIOGRAPHYField;
            }
            set {
                this.bIOGRAPHYField = value;
            }
        }
        
        /// <remarks/>
        public string ALIASNAME {
            get {
                return this.aLIASNAMEField;
            }
            set {
                this.aLIASNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string THUMBNAIL_PATH {
            get {
                return this.tHUMBNAIL_PATHField;
            }
            set {
                this.tHUMBNAIL_PATHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GENRE {
        
        private int gENREIDField;
        
        private string nAMEField;
        
        private string dESCRIPTIONField;
        
        private string rEFERENCE_KEYField;
        
        /// <remarks/>
        public int GENREID {
            get {
                return this.gENREIDField;
            }
            set {
                this.gENREIDField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string REFERENCE_KEY {
            get {
                return this.rEFERENCE_KEYField;
            }
            set {
                this.rEFERENCE_KEYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CATEGORY {
        
        private int cATEGORYIDField;
        
        private string nAMEField;
        
        private string dESCRIPTIONField;
        
        private string rEFERENCE_KEYField;
        
        private string cATEGORY_THUMBNAILField;
        
        /// <remarks/>
        public int CATEGORYID {
            get {
                return this.cATEGORYIDField;
            }
            set {
                this.cATEGORYIDField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string REFERENCE_KEY {
            get {
                return this.rEFERENCE_KEYField;
            }
            set {
                this.rEFERENCE_KEYField = value;
            }
        }
        
        /// <remarks/>
        public string CATEGORY_THUMBNAIL {
            get {
                return this.cATEGORY_THUMBNAILField;
            }
            set {
                this.cATEGORY_THUMBNAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetRolesCompletedEventHandler(object sender, GetRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ROLE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ROLE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USER[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USER[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetCategoriesCompletedEventHandler(object sender, GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CATEGORY[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CATEGORY[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateCategoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserCategoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteCategoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetGenresCompletedEventHandler(object sender, GetGenresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GENRE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GENRE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateGenreCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserGenreCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteGenreCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAuthorsCompletedEventHandler(object sender, GetAuthorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AUTHOR[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AUTHOR[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteAuthorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddAuthorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateAuthorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetProducersCompletedEventHandler(object sender, GetProducersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProducersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProducersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PRODUCER[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PRODUCER[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteProducerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertProducerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateProducerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591